import type { Metadata } from 'next';
// import { Inter, Jost } from 'next/font/google';
import { Jost } from 'next/font/google';
import './globals.css';

const jost = Jost({ subsets: ['latin'], display: 'swap' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log(jost.className);
  return (
    <html lang="en">
      <body className={jost.className}>{children}</body>
    </html>
  );
}
